name: Test GoKit

on:
  push:
    branches: [ master, develop ]

  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing

    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: gokit_test

    steps:
    - uses: actions/checkout@v4

    - name: Start MySQL
      run: sudo /etc/init.d/mysql start

    - name: Create MySQL Database
      run: mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u $DB_USERNAME -p$DB_PASSWORD

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Clean test cache
      run: go clean -testcache

    - name: Install modules
      run: go mod download

    - name: Run GoKit Tests
      run: go test ./tests -v
